# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56aba0d967a4928a82d354ec774583f4"
name = "Tag MetaField Manager"
application_url = "https://tag-metafield-manager-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "/webhooks/app/subscriptions/update"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_own_subscription_contracts,write_own_subscription_contracts,write_markets,read_markets,read_content,write_locations,write_content,write_products,read_customers,read_draft_orders,read_orders,read_products,read_customer_merge,write_customers,write_draft_orders,write_orders,read_content,write_content,read_locations,read_companies,write_companies,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"
[auth]
redirect_urls = [ "https://example.com/api/auth" ]
